# Default values for secrets-manager component
# List of applications that need OAuth client secrets
applications:
  - name: grafana
    namespace: monitoring
  - name: pgadmin
    namespace: pgadmin
  - name: oauth2-proxy
    namespace: keycloak
