ArgocdApplications:

  keycloak:
    enabled: true
    syncWave: 1

  keycloakx:
    enabled: false

  keycloak-operator:
      enabled: true

  olm:
    enabled: true
    plugin:
      name: kustomize
      parameters:
        patches: |-
          # Patch for olm-operator deployment
          - patch: |-
              - op: add
                path: /spec/template/spec/containers/0/ports/0/protocol
                value: TCP
            target:
              kind: Deployment
              name: olm-operator
              namespace: olm

          # Patch for catalog-operator deployment
          - patch: |-
              - op: add
                path: /spec/template/spec/containers/0/ports/0/protocol
                value: TCP
            target:
              kind: Deployment
              name: catalog-operator
              namespace: olm

  cnpg-database:
    enabled: true
    path: values/onprem/platform/database/

  raw:
    enabled: true
    path: values/onprem/platform/raw

  dashboards:
    enabled: true

  metrics-server:
    enabled: true

  metallb:
    enabled: true

  external-dns:
    enabled: true

  argocd-image-updater:
    enabled: true

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true
    # ignoreDifferences:
    #   - group: ""
    #     kind: Service
    #     jqPathExpressions:
    #       - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: false

  sealed-secrets:
    enabled: false

  ingresses:
    enabled: true

  vault:
    enabled: false

  # Microservices

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true
