kustomize:

  hello:
    enabled: false
    path: values/local-example/applications/dev/hello

  cnpg-database:
    enabled: true
    path: values/local-example/platform/database/

  raw:
    enabled: false
    path: values/local-example/platform/raw

  dashboards:
    enabled: true

helm:

  argocd-image-updater:
    enabled: false

  keycloak:
    enabled: true

  keycloak-operator:
    enabled: false

  ingress-nginx:
    enabled: true
    ignoreDifferences:
      - group: ""
        kind: Service
        jqPathExpressions:
          - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: false

  cert-manager:
    enabled: true

  backstage:
    enabled: false

  sealed-secrets:
    enabled: false

  ingresses:
    enabled: true

  vault:
    enabled: false

  # Microservice examples

  show-env:
    enabled: false
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  backend:
    enabled: false

  identityserver:
    enabled: true

  openiddictserver:
    enabled: true
