global:
  platformName: x
  automated: true
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: x
      targetRevision: x
    values:
      repoURL: x
      targetRevision: x

applications:
  # A Kustomize application example
  hello:
    enabled: false

  cnpg-database:
    enabled: false
    namespace: cloudnative-pg

  raw:
    enabled: true


helmCharts:

  teams-namespaces:
    enabled: false
    namespace: default

  backstage:
    enabled: false
    # syncWave: 1

  keycloak:
    enabled: false
    syncWave: 0
    path: templates/keycloak

  keycloak-operator:
    enabled: false

  sealed-secrets:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.3.5
    chart: sealed-secrets

  ingress-nginx:
    enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.1
    chart: ingress-nginx

  kube-prometheus-stack:
    enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 56.7.0
    chart: kube-prometheus-stack

  loki:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.78.2
    chart: loki-distributed

  promtail:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.15.5
    chart: promtail

  harbor:
    enabled: false
    repoURL: https://helm.goharbor.io
    namespace: harbor
    targetRevision: 1.14.2
    chart: harbor

  cert-manager:
    enabled: false
    namespace: cert-manager

  actions-runner-controller:
    enabled: false
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    namespace: actions-runner-system
    targetRevision: 0.22.0
    chart: actions-runner-controller
    syncWave: 0

  actions-runner:
    enabled: false
    repoURL: https://github.com/kuberise/kuberise.git
    namespace: actions-runner-system
    syncWave: 1

  gitea:
    enabled: false
    repoURL: https://dl.gitea.io/charts
    namespace: gitea
    targetRevision: 10.1.4
    chart: gitea

  cloudnative-pg:
    enabled: false
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg

  pgadmin:
    enabled: false

  ingresses:
    enabled: false

  # Microservice helm charts for the dev environment

  echo:
    enabled: false
    path: templates/generic-deployment

  todolist-frontend-dev:
    enabled: false
    path: templates/generic-deployment

  todolist-backend-dev:
    enabled: false
    path: templates/generic-deployment

  show-env-dev:
    enabled: false
    path: templates/generic-deployment

# Microservice helm charts for the tst environment

  todolist-frontend-tst:
    enabled: false
    path: templates/generic-deployment

# Microservice helm charts for the prd environment

  todolist-frontend-prd:
    enabled: false
    path: templates/generic-deployment
