global:
  env: dta
  automated: true
  spec:
    project: platform-dta
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/kuberise/kuberise.git
      targetRevision: mojtaba/configuration
    values:
      repoURL: https://github.com/kuberise/kuberise.git
      targetRevision: mojtaba/configuration

applications:

  # helm-guestbook:
  #   enabled: true

helmCharts:
  teams-namespaces:
    enabled: true
    namespace: default

  keycloak:
    enabled: true
    repoURL: registry-1.docker.io/bitnamicharts
    chart: keycloak
    targetRevision: 16.0.3

  sealed-secrets:
    enabled: true
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.11.0
    chart: sealed-secrets

  airflow:
    enabled: true
    repoURL: https://airflow.apache.org
    targetRevision: 1.10.0
    chart: airflow

  nginx-ingress:
    enabled: true
    repoURL: ghcr.io/nginxinc/charts
    targetRevision: 0.18.0
    chart: nginx-ingress

  kube-prometheus-stack:
    enabled: true
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 48.3.3
    chart: kube-prometheus-stack

  loki:
    enabled: true
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.71.1
    chart: loki-distributed

  promtail:
    enabled: true
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.14.1
    chart: promtail
