kustomize:

  cnpg-database:
    enabled: false
    path: values/prd/platform/database/

  raw:
    enabled: false
    path: values/prd/platform/raw

  dashboards:
    enabled: false

helm:

  external-dns:
    enabled: true

  internal-dns:
    enabled: true

  argocd-image-updater:
    enabled: true

  keycloak:
    enabled: false

  keycloak-operator:
    enabled: false

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: false

  pgadmin:
    enabled: false

  cert-manager:
    enabled: true

  ingresses:
    enabled: true

  # Microservices

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:x.y.z
      argocd-image-updater.argoproj.io/update-strategy: semver
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true
