kustomize:

  cnpg-database:
    enabled: true
    path: values/onprem/platform/database/

  raw:
    enabled: true
    path: values/onprem/platform/raw

  dashboards:
    enabled: true

helm:
  external-dns:
    enabled: true

  argocd-image-updater:
    enabled: true

  keycloak:
    enabled: true

  keycloak-operator:
    enabled: true

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true
    ignoreDifferences:
      - group: ""
        kind: Service
        jqPathExpressions:
          - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: true

  sealed-secrets:
    enabled: true

  ingresses:
    enabled: true

  vault:
    enabled: true

  # Microservices

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true
