global:
  env: dta


helmCharts:
  keycloak:
    enabled: false
  airflow:
    enabled: false
  nginx-ingress:
    enabled: true
    valuesTargetRevision: mojtaba/configuration
  helm-guestbook:
    enabled: true
    targetRevision: mojtaba/configuration
    valuesTargetRevision: mojtaba/configuration
    name: guestbook
    namespace: guestbook
