ArgocdApplications:

  keycloak:
    enabled: true
    # syncWave: 1

  keycloak-operator:
    enabled: true

  database:
    enabled: true

  raw:
    enabled: true

  dashboards:
    enabled: true

  metrics-server:
    enabled: true

  metallb:
    enabled: true
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle

  external-dns:
    enabled: true

  argocd-image-updater:
    enabled: true

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true


  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  postgres-operator:
    enabled: true

  pgadmin:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: false

  vault:
    enabled: false

  # Microservices

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true

  external-secrets:
    enabled: true
