applications:
  cnpg-database:
    enabled: true

helmCharts:
  keycloak:
    enabled: false

  ingress-nginx:
    enabled: true

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: false

  todolist-frontend-dev:
    enabled: true

  todolist-frontend-tst:
    enabled: true

  todolist-frontend-prd:
    enabled: true

  show-env-dev:
    enabled: true

  cert-manager:
    enabled: true

  backstage:
    enabled: false

  gitea:
    enabled: false

  harbor:
    enabled: false
