# some of the values will be filled by install.sh script
global:
  platformName: x
  domain: x
  automated: true
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: x
      targetRevision: x
    values:
      repoURL: x
      targetRevision: x

# There are three types of ArgocdApplications: kustomize, helm, and raw. Default is helm
ArgocdApplications:
  hello:
    enabled: false
    type: kustomize

  cnpg-database:
    enabled: false
    namespace: cloudnative-pg
    type: raw

  raw:
    enabled: false
    type: raw

  dashboards:
    enabled: false
    namespace: monitoring
    type: kustomize

  metrics-server:
    enabled: false
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.2
    chart: metrics-server

  metallb:
    enabled: false

  internal-dns:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.5.1
    chart: external-dns

  external-dns:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.5.1
    chart: external-dns

  argocd-image-updater:
    enabled: false
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.11.1
    chart: argocd-image-updater
    namespace: argocd

  teams-namespaces:
    enabled: false
    namespace: default

  backstage:
    enabled: false
    # syncWave: 1

  keycloak:
    enabled: false
    syncWave: 0

  keycloak-operator:
    enabled: false

  sealed-secrets:
    enabled: false
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.40.10
    chart: sealed-secrets

  ingress-nginx-external:
    enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx

  ingress-nginx-internal:
    enabled: false
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    chart: ingress-nginx

  kube-prometheus-stack:
    enabled: false
    repoURL: https://prometheus-community.github.io/helm-charts
    namespace: monitoring
    targetRevision: 65.8.1
    chart: kube-prometheus-stack

  loki:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 0.79.4
    chart: loki-distributed

  promtail:
    enabled: false
    repoURL: https://grafana.github.io/helm-charts
    namespace: monitoring
    targetRevision: 6.16.6
    chart: promtail

  cert-manager:
    enabled: false
    namespace: cert-manager

  actions-runner-controller:
    enabled: false
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    namespace: actions-runner-system
    targetRevision: 0.22.0
    chart: actions-runner-controller
    syncWave: 0

  actions-runner:
    enabled: false
    repoURL: https://github.com/kuberise/kuberise.git
    namespace: actions-runner-system
    syncWave: 1

  gitea:
    enabled: false
    repoURL: https://dl.gitea.io/charts
    namespace: gitea
    targetRevision: 10.1.4
    chart: gitea

  cloudnative-pg:
    enabled: false
    repoURL: https://cloudnative-pg.github.io/charts
    namespace: cloudnative-pg
    targetRevision: 0.20.1
    chart: cloudnative-pg

  pgadmin:
    enabled: false

  ingresses:
    enabled: false

  vault:
    enabled: false
    repoURL: https://helm.releases.hashicorp.com
    namespace: vault
    targetRevision: 0.28.0
    chart: vault

  # Microservice examples

  # http container example with external traffic
  show-env:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  # https container example with external traffic that receives traffic over https from ingress controller

  frontend-https:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  # a sample of microservice with internal traffic
  backend:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications

  # a sample of microservice with internal traffic
  api:
    enabled: false
    path: templates/generic-deployment
    valuesFolder: applications
