kustomize:

  hello:
    enabled: false
    path: values/local-example/applications/dev/hello

  cnpg-database:
    enabled: true
    path: values/local-example/platform/database/

  raw:
    enabled: false
    path: values/local-example/platform/raw

  dashboards:
    enabled: true

helm:
  keycloak:
    enabled: true

  keycloak-operator:
    enabled: false

  ingress-nginx:
    enabled: true
    ignoreDifferences:
      - group: ""
        kind: Service
        jqPathExpressions:
          - .status.loadBalancer.ingress[].ipMode

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cloudnative-pg:
    enabled: true

  pgadmin:
    enabled: false

  cert-manager:
    enabled: true

  backstage:
    enabled: false

  sealed-secrets:
    enabled: false

  ingresses:
    enabled: true

  vault:
    enabled: false

  # Microservice helm charts for the dev environment

  todolist-frontend-dev:
    enabled: false

  todolist-backend-dev:
    enabled: false

  show-env-dev:
    enabled: false

# Microservice helm charts for the tst environment

  todolist-frontend-tst:
    enabled: false


# Microservice helm charts for the prd environment

  todolist-frontend-prd:
    enabled: false
