kustomize:

  cnpg-database:
    enabled: false
    path: values/aks/platform/database/

  raw:
    enabled: false
    path: values/aks/platform/raw

  dashboards:
    enabled: true

helm:

  external-dns:
    enabled: true

  internal-dns: # bitnami chart doesn't work well with azure-private-dns provider
    enabled: true
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.15.0
    chart: external-dns

  argocd-image-updater:
    enabled: true

  keycloak:
    enabled: false

  keycloak-operator:
    enabled: false

  ingress-nginx-internal:
    enabled: true

  ingress-nginx-external:
    enabled: true

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: false

  pgadmin:
    enabled: false

  cert-manager:
    enabled: true

  ingresses:
    enabled: true

  # Microservices

  show-env:
    enabled: true
    annotations:
      argocd-image-updater.argoproj.io/image-list: ghcr.io/kuberise/show-env:latest
      argocd-image-updater.argoproj.io/update-strategy: digest
      argocd-image-updater.argoproj.io/write-back-method: git

  frontend-https:
    enabled: true

  backend:
    enabled: true

  api:
    enabled: true
