apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-action-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: g-runner
      automountServiceAccountToken: true
      repository: {{ index .Values "runner-deployment" "repository" }}
      labels:
      - "actions_runner_dev"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: g-runner
subjects:
- kind: ServiceAccount
  name: g-runner
  namespace: actions-runner-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g-runner
  namespace: actions-runner-system