apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
spec:
  commonName: ca.example.com
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  secretName: ca-key-pair
  duration: 24000h # 1000 days
  renewBefore: 360h # 15 days
---
# apiVersion: cert-manager.io/v1
# kind: Issuer
# metadata:
#   name: ca-issuer
# spec:
#   ca:
#     secretName: ca-key-pair
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-cert
# spec:
#   secretName: wildcard-cert-tls
#   duration: 2160h # 90 days
#   renewBefore: 360h # 15 days
#   commonName: "*.127.0.0.1.nip.io"
#   dnsNames:
#   - "127.0.0.1.nip.io"
#   - "*.127.0.0.1.nip.io"
#   - "*.dev.127.0.0.1.nip.io"
#   - "*.tst.127.0.0.1.nip.io"
#   - "*.acc.127.0.0.1.nip.io"
#   issuerRef:
#     name: ca-issuer
#     kind: Issuer
#     group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-clusterissuer
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: argocd
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: monitoring
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: keycloak
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: todolist-frontend-dev
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: todolist-frontend-tst
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: todolist-frontend-prd
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: show-env-dev
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: backstage
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
