apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
spec:
  commonName: ca.example.com
  isCA: true
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  secretName: ca-key-pair
  duration: 24000h # 1000 days
  renewBefore: 360h # 15 days
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-cert-tls
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: "*.127.0.0.1.nip.io"
  dnsNames:
  - "127.0.0.1.nip.io"
  - "*.127.0.0.1.nip.io"
  - "*.dev.127.0.0.1.nip.io"
  - "*.tst.127.0.0.1.nip.io"
  - "*.acc.127.0.0.1.nip.io"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
