redis:
  global:
    imageRegistry: registry:5000
    security:
      allowInsecureImages: true

  architecture: standalone
  auth:
    enabled: true

  master:
    persistence:
      enabled: false

  replica:
    replicaCount: 0

  sentinel:
    enabled: false
