replicaCount: 2

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
  tls:
  - hosts:
    - "*.{{ .Values.global.domain }}"
    secretName: wildcard-cert-tls
  hosts:
    - host: frontend-tst.{{ .Values.global.domain }}
      paths:
        - path: /
          pathType: ImplementationSpecific
