replicaCount: 2

ingress:
  enabled: true
  tls:
  - hosts:
    - "*.kind.kuberise.dev"
  hosts:
    - host: frontend-tst.kind.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific

image:
  repository: ghcr.io/kuberise/todolist-webapp
  tag: "latest"
