apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: project1-dev
  source:
    helm:
      repoURL: https://kubernetes-charts.storage.googleapis.com
      chart: keycloak
      targetRevision: 9.0.0
      values:
        - ./app-values/keycloak/keycloak-values-project1-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptins:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
        backoff:
          duration: 30
          factor: 2
          maxDuration: 60
