apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: project1-dev
  source:
    helm:
      repoURL: https://kubernetes-charts.storage.googleapis.com
      chart: nginx-ingress
      targetRevision: 1.41.3
      values:
        - ./app-values/nginx-ingress/nginx-ingress-values-project1-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
        backoff:
          duration: 30
          factor: 2
          maxDuration: 60
