cert-manager:
  installCRDs: true
  namespace: cert-manager

selfSignedCertificate:
  enabled: false

# list of namespaces to create the certificate
namespaces: []

# certificate configuration
certificate: {}
