apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: {{ .Values.argocd.appProject.name }}-{{ .Values.environment }}
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    sourceRepos:
    - '*'
    destinations:
    - name: '*'
      namespace: '*'
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
