apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
---
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-repo-kuberise
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: kuberise
  url: https://github.com/kuberise/kuberise.git
  type: git
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-database-app
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
data:
  dbname: {{ "*" | b64enc | quote }}
  host: {{ "cnpg-database-rw" | b64enc | quote }}
  username: {{ "app" | b64enc | quote }}
  user: {{ "app" | b64enc | quote }}
  port: {{ "5432" | b64enc | quote }}
  password: {{ .Values.adminPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-database-superuser
  namespace: cloudnative-pg
type: kubernetes.io/basic-auth
data:
  dbname: {{ "*" | b64enc | quote }}
  host: {{ "cnpg-database-rw" | b64enc | quote }}
  username: {{ "postgres" | b64enc | quote }}
  user: {{ "postgres" | b64enc | quote }}
  port: {{ "5432" | b64enc | quote }}
  password: {{ .Values.pgSuperuserPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: backstage
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.adminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: keycloak
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.adminPassword }}
