apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-app-delete
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: argocd-job
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
          - /bin/bash
          - -c
          - |
            kubectl delete application app-of-apps-dta -n argocd || true
            kubectl delete appproject platform-dta -n argocd || true
      restartPolicy: Never
