keycloak:

  externalDatabase:
    host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
    user: app
    database: app
    existingSecret: pg-secret
    existingSecretPasswordKey: password

  auth:
    adminUser: admin
    existingSecret: pg-secret
    passwordSecretKey: password

  ingress:
    enabled: true
    ingressClassName: "nginx"
    pathType: ImplementationSpecific
    apiVersion: ""
    path: "{{ .Values.httpRelativePath }}"
    servicePort: http
    hostname: keycloak.127.0.0.1.nip.io
    extraTls:
    - hosts:
      - "*.127.0.0.1.nip.io"
      secretName: wildcard-cert-tls
