keycloak:

  externalDatabase:
    host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
    user: app
    database: app
    existingSecret: pg-secret
    existingSecretPasswordKey: password

  auth:
    adminUser: admin
    existingSecret: pg-secret
    passwordSecretKey: password

  tls:
    enabled: true
    existingSecret: wildcard-cert-tls

  # ingress:
  #   enabled: true
  #   ingressClassName: "nginx"
  #   path: "{{ .Values.httpRelativePath }}"
  #   servicePort: http
  #   # ingress.annotations: {}
  #   tls: true
  #   hostname: keycloak.127.0.0.1.nip.io
  #   secrets:
  #   - name: wildcard-cert-tls
  #     secretName: wildcard-cert-tls
  #     hosts:
  #     - "keycloak.127.0.0.1.nip.io"
  #   # extraTls:
  #   # - hosts:
  #   #   - "*.127.0.0.1.nip.io"
  #   #   secretName: wildcard-cert-tls

  # adminIngress:
  #   enabled: true
  #   ingressClassName: "nginx"
  #   path: /
  #   servicePort: https
  #   tls: true
  #   hostname: keycloak-admin.127.0.0.1.nip.io
  #   secrets:
  #   - name: wildcard-cert-tls
  #     secretName: wildcard-cert-tls
  #     hosts:
  #     - "keycloak-admin.127.0.0.1.nip.io"
  #   # extraTls:
  #   # - hosts:
  #   #   - "*.127.0.0.1.nip.io"
  #   #   secretName: wildcard-cert-tls
