replicaCount: 2

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: ca-clusterissuer
  tls:
  - hosts:
    - "*.tst.172.19.0.5.nip.io"
    secretName: wildcard-cert-tls
  hosts:
    - host: frontend.tst.172.19.0.5.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
