replicaCount: 2

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: ca-clusterissuer
  tls:
  - hosts:
    - "*.tst.127.0.0.1.nip.io"
    secretName: wildcard-cert-tls
  hosts:
    - host: frontend.tst.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
