{{- range .Values.services }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}
  namespace: {{ default .name .namespace }}
  {{- if .annotations }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
spec:
  ingressClassName: {{ default "nginx" .ingressClassName }}
  rules:
  - host: {{ default .name .subdomain }}.{{ $.Values.domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ default .name .serviceName }}
            port:
              number: {{ default 80 .port }}
        path: {{ default "/" .path }}
        pathType: Prefix
  tls:
  - hosts:
    - {{ default .name .subdomain }}.{{ $.Values.domain }}
    secretName: {{ default "" .secretName }}
---
{{- end }}

# TODO: if there is secretname add the secret name to the tls section
