apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: pgadmin-client
spec:
  targetRealm: realm-platform  # Changed from 'realm' to 'targetRealm'
  clientId: pgadmin
  public: false
  redirectUris:
    - "http://pgadmin-pgadmin4.pgadmin.svc.cluster.local/*"
  webOrigins:
    - "http://pgadmin-pgadmin4.pgadmin.svc.cluster.local"
  defaultClientScopes:
    - email
    - profile
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmRole
metadata:
  name: pgadmin-admin
spec:
  name: pgadmin-admin
  realm: realm-platform
  composite: false
  attributes:
    - key: description
      value: "PgAdmin Administrator Role"
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmGroup
metadata:
  name: pgadmin-admins
spec:
  name: PgAdminAdmins
  realm: realm-platform
  realmRoles:
    - pgadmin-admin
