grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-gateway
        isDefault: false
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - grafana.127.0.0.1.nip.io
    path: /
  # adminPassword: ""
  # admin:
  #   existingSecret: grafana-admin
  #   passwordKey: admin-password
  #   userKey: admin-user

  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Kuberise
      org_role: Admin
    security:
      disable_initial_admin_creation: true
    auth.basic:
      enabled: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.127.0.0.1.nip.io
    paths:
      - /
    pathType: Prefix
