services:
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
  - name: keycloak
    serviceName: keycloak-keycloakx-http
  # - name: backend-https
  #   port: 4443
  #   annotations:
  #     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  - name: grafana
    namespace: monitoring
    serviceName: kube-prometheus-stack-grafana
  - name: prometheus
    namespace: monitoring
    subdomain: prometheus
    serviceName: kube-prometheus-stack-prometheus
    port: 9090
  # - name: backstage
  #   port: 7007
  # - name: pgadmin
  #   serviceName: pgadmin-pgadmin4
  # - name: vault
  #   port: 8200
