services:
  - name: argocd-server
    namespace: argocd
    subdomain: argocd
  - name: backstage
    port: 7007
  - name: keycloak
    serviceName: keycloak-keycloakx-http
    port: 8443
    annotations:
      nginx.ingress.kubernetes.io/app-root: /auth/
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      # nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/auth-tls-secret: "cert-manager/ca-key-pair-external"
      # nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
      # nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
      # nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
  - name: grafana
    namespace: monitoring
    serviceName: kube-prometheus-stack-grafana
  - name: prometheus
    namespace: monitoring
    subdomain: prometheus
    serviceName: kube-prometheus-stack-prometheus
    port: 9090
  - name: pgadmin
    serviceName: pgadmin-pgadmin4
  - name: show-env-dev
  # - name: todolist-frontend-dev
  - name: hello
    port: 8080
  # - name: echo
  #   port: 8080
  # - name: todolist-backend-dev
  # - name: vault
  #   port: 8200
