ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backstage.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
service:
  type: ClusterIP
  port: 7007

backstage:
  appConfig:
    app:
      baseUrl: https://backstage.127.0.0.1.nip.io
    backend:
      baseUrl: https://backstage.127.0.0.1.nip.io
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
      cors:
        origin: https://backstage.127.0.0.1.nip.io
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        credentials: true
      database:
        client: pg
        connection:
          host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
          port: 5432
          user: app
          existingSecret: pg-secret
          existingSecretPasswordKey: password
    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: dev
      rules:
        - allow:
          - Component
          - API
          - Resource
          - System
          - Domain
          - Location
