ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backstage.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
service:
  type: ClusterIP
  port: 7007

backstage:
  appConfig:
    app:
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      csp:
        connect-src: ["'self'", 'http:', 'https:']
    db:
      connection:
        host: cnpg-database-rw.cloudnative-pg.svc.cluster.local
        port: 5432
        user: app
        existingSecret: pg-secret
        existingSecretPasswordKey: password
