# Default values for cert-manager
cert-manager:
  # Add any custom values for cert-manager here
  installCRDs: true
  namespace: cert-manager

selfSignedCertificate:
  enabled: false
  generateCA: false

letsEncrypt:
  enabled: false
  email: a@b.com
  server: production # production or staging
  challenge: http01 # http01 or dns01

# list of namespaces to create the certificate
namespaces: []

# certificate configuration
certificate: {}

subdomains: [] # subdomains to include in the certificate
