cilium:
  operator:
    replicas: 1

  hubble:
    enabled: true
    relay:
      enabled: true
    ui:
      enabled: true
      securityContext:
        apparmor:
          enabled: false
      ingress:
        enabled: true
        className: nginx-external
        hosts:
          - hubble.onprem.kuberise.dev
