replicaCount: 1

ingress:
  enabled: true
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer"
  tls:
  - hosts:
    - "*.nip.io"
    secretName: wildcard-cert-tls
  hosts:
    - host: frontend-dev-127-0-0-1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
