configs:
  cm:
    timeout.reconciliation: 5s
    url: https://argocd.eks.kuberise.dev
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.eks.kuberise.dev/realms/platform
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
      requestedIDTokenClaims:
        groups:
          essential: true
      groupsAttributePath: groups
