apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      # the store is able to pull only from this namespace
      remoteNamespace: raw
      auth:
        serviceAccount:
          name: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: raw
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: raw
  - kind: ServiceAccount
    name: external-secrets
    namespace: keycloak
  - kind: ServiceAccount
    name: external-secrets
    namespace: monitoring
  - kind: ServiceAccount
    name: external-secrets
    namespace: pgadmin
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
