# ==========================================
# Generate Secret
# ==========================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-es
spec:
  refreshInterval: "0" # 0 means the secret is not re-generated
  target:
    name: pgadmin-random-string
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
---
# ==================================================================================================
# Copy secrets for keycloak namespace and also for the application namespace
# ==================================================================================================
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: pgadmin-client-secret-ces
spec:
  externalSecretName: pgadmin-client-secret-es

  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: keycloak
    - matchLabels:
        kubernetes.io/metadata.name: pgadmin

  refreshTime: "1m"
  externalSecretSpec:
    secretStoreRef:
      name: k8s-store
      kind: ClusterSecretStore

    refreshInterval: "1h"
    target:
      name: pgadmin-oauth2-client-secret
      creationPolicy: Owner
    data:
      - secretKey: client-secret
        remoteRef:
          key: pgadmin-random-string
          property: password
          conversionStrategy: Default
          decodingStrategy: None
          metadataPolicy: None
