# apiVersion: v1
# data:
#   password: YWRtaW4=
#   username: YWRtaW4=
# kind: Secret
# metadata:
#   creationTimestamp: null
#   name: keycloak-access
#   namespace: keycloak-operator
# ---
# apiVersion: v1.edp.epam.com/v1
# kind: Keycloak
# metadata:
#   name: keycloak-instance
#   namespace: keycloak-operator
# spec:
#   secret: keycloak-access             # Secret name
#   url: http://keycloak-keycloakx-http.keycloak.svc.cluster.local/auth/   # Keycloak URL
# ---
# apiVersion: v1.edp.epam.com/v1
# kind: KeycloakRealm
# metadata:
#   name: platform
#   namespace: keycloak-operator
# spec:
#  realmName: platform
#  keycloakRef:
#    name: keycloak-instance
#    kind: Keycloak
# ---
# apiVersion: v1.edp.epam.com/v1
# kind: KeycloakRealmGroup
# metadata:
#   namespace: keycloak-operator
#   name: platform-admins
# spec:
#   name: PlatformAdmins
#   realmRef:
#     name: platform
#     kind: KeycloakRealm
# ---
# apiVersion: v1.edp.epam.com/v1
# kind: KeycloakClient
# metadata:
#   name: pgadmin
#   namespace: keycloak-operator
# spec:
#   authorization:
#     permissions:
#       - decisionStrategy: AFFIRMATIVE
#         description: Resource permission
#         logic: POSITIVE
#         name: pgadmin-resource-permission
#         policies:
#           - role-policy
#         resources:
#           - pgadmin-resource
#         type: resource
#       - decisionStrategy: CONSENSUS
#         description: Scope permission
#         logic: POSITIVE
#         name: pgadmin-scope-permission
#         policies:
#           - role-policy
#         scopes:
#           - pgadmin-scope
#         type: scope
#     policies:
#       - decisionStrategy: AFFIRMATIVE
#         description: Role policy
#         logic: POSITIVE
#         name: pgadmin-role-policy
#         rolePolicy:
#           roles:
#             - name: admin
#               required: true
#         type: role
#       - aggregatedPolicy:
#           policies:
#             - policy1
#             - policy2
#         description: Aggregate policy
#         name: pgadmin-aggregate-policy
#         type: aggregate
#       - clientPolicy:
#           clients:
#             - pgadmin
#         description: Client policy
#         name: pgadmin-client-policy
#         type: client
#       - description: Group policy
#         groupPolicy:
#           groups:
#             - extendChildren: true
#               name: pgadmin-group
#         name: pgadmin-group-policy
#         type: group
#       - description: Role policy
#         name: pgadmin-role-policy
#         rolePolicy:
#           roles:
#             - name: admin
#               required: true
#         type: role
#       - description: Time policy
#         name: pgadmin-time-policy
#         timePolicy:
#           notBefore: '2023-01-01T00:00:00Z'
#           notOnOrAfter: '2024-12-31T23:59:59Z'
#         type: time
#       - description: User policy
#         name: pgadmin-user-policy
#         type: user
#         userPolicy:
#           users:
#             - user1
#             - user2
#   authorizationServicesEnabled: true
#   clientId: pgadmin
#   directAccess: true
#   realmRef:
#     kind: KeycloakRealm
#     name: platform
#   secret: '$client-secret-pgadmin:client-secret-key'
#   serviceAccount:
#     enabled: true
#   webUrl: 'http://pgadmin.minikube.kuberise.dev'
# ---
