grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-gateway
        isDefault: false
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
    - hosts:
      - "*.kind.kuberise.dev"
    hosts:
      - grafana.kind.kuberise.dev
    path: /
    pathType: Prefix

  adminPassword: ""
  admin:
    existingSecret: grafana-admin
    passwordKey: admin-password
    userKey: admin-user

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
    - hosts:
      - "*.kind.kuberise.dev"
    hosts:
      - prometheus.kind.kuberise.dev
    paths:
      - /
    pathType: Prefix
