grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-loki-distributed-gateway
        isDefault: false
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
    ingressClassName: nginx
    tls:
    - hosts:
      - "*.kind.kuberise.dev"
      secretName: wildcard-cert-tls-grafana
    hosts:
      - grafana.kind.kuberise.dev
    path: /
    pathType: Prefix

  adminPassword: ""
  admin:
    existingSecret: grafana-admin
    passwordKey: admin-password
    userKey: admin-user

prometheus:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
    ingressClassName: nginx
    tls:
    - hosts:
      - "*.kind.kuberise.dev"
      secretName: wildcard-cert-tls-prometheus
    hosts:
      - prometheus.kind.kuberise.dev
    paths:
      - /
    pathType: Prefix
