pgadmin4:
  ingress:
    enabled: true
    ingressClassName: external-nginx
    annotations:
      cert-manager.io/cluster-issuer: http-01-production
    hosts:
      - host: pgadmin.eks.kuberise.dev
        paths:
          - path: /
            pathType: Prefix
