apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-instance
  namespace: keycloak
spec:
  secret: keycloak-access             # Secret name
  url: https://keycloak-keycloakx-http:8443
  caCert:
    secretKeyRef:
      name: keycloak-tls
      key: tls.crt
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
 name: platform-realm
 namespace: keycloak
spec:
 realmName: platform
 keycloakRef:
   name: keycloak-instance
   kind: Keycloak
---
