apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-instance
  namespace: keycloak
spec:
  secret: keycloak-access             # Secret name
  url: https://keycloak.onprem.kuberise.dev
