useHttps: false

containerPorts:
  http: 80

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  className: nginx-internal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: "kuberise.internal"
    external-dns.alpha.kubernetes.io/internal-hostname: "true"
  hosts:
    - host: kuberise.internal
      paths:
        - path: /backend
          pathType: Prefix
  tls: []
