apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: ca-clusterissuer-external
  name: argocd-server
  namespace: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: {{ printf "argocd.%s" .Values.global.domain | quote }}
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ printf "argocd.%s" .Values.global.domain | quote }}
    secretName: argocd-server-tls
