

ingress:
    enabled: true
    web:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

      ingressClassName: "nginx"
      host: "airflow.127.0.0.1.nip.io"
      path: "/airflow"
