apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  namespace: pgadmin
data:
  config_local.py: |
    import os
    import logging

    FILE_LOG_LEVEL = logging.INFO
    SERVER_MODE = True
    CONSOLE_LOG_LEVEL = logging.INFO
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['internal', 'oauth2']
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'Keycloak',
        'OAUTH2_DISPLAY_NAME': 'Keycloak',
        'OAUTH2_CLIENT_ID': 'pgadmin',
        'OAUTH2_CLIENT_SECRET': '3OpIsTcAUM81lB2E1sXpbdipQe37JLmF',
        'OAUTH2_TOKEN_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/auth',
        'OAUTH2_SERVER_METADATA_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/.well-known/openid-configuration',
        'OAUTH2_API_BASE_URL': 'https://keycloak.onprem.kuberise.dev/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_USERNAME_CLAIM': 'preferred_username',
        'OAUTH2_LOGOUT_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/logout?post_logout_redirect_uri=https://keycloak.onprem.kuberise.dev&id_token_hint={id_token}&client_id={pgadmin}',
        'OAUTH2_ICON': 'fa-solid fa-unlock',
        'OAUTH2_BUTTON_COLOR': '#f44242',
        'OAUTH2_SSL_CERT_VERIFICATION': False, # for self-signed certificates it should be False
      }
    ]
