apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  namespace: pgadmin
data:
  config_oauth2.py: |
    AUTHENTICATION_SOURCES = ['oauth2']
    OAUTH2_AUTO_CREATE_USER = True

    # PgAdmin expects OAUTH2_CONFIG to be a list of configurations
    OAUTH2_CONFIG = [{
        'OAUTH2_NAME': 'Keycloak',
        'OAUTH2_DISPLAY_NAME': 'Keycloak',
        'OAUTH2_CLIENT_ID': 'pgadmin',
        'OAUTH2_CLIENT_SECRET': 'ihHuyvj4EcaGpKR5QVA4DeGDRxelz0Iv',

        # Internal Keycloak URLs
        'OAUTH2_TOKEN_URL': 'https://keycloak-keycloakx-http.keycloak.svc.cluster.local:8443/realms/master/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.onprem.kuberise.dev/realms/master/protocol/openid-connect/auth',
        'OAUTH2_API_BASE_URL': 'https://keycloak-keycloakx-http.keycloak.svc.cluster.local:8443/realms/master/protocol/openid-connect',
        'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak-keycloakx-http.keycloak.svc.cluster.local:8443/realms/master/protocol/openid-connect/userinfo',

        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_USERNAME_CLAIM': 'preferred_username',
        'OAUTH2_EMAIL_CLAIM': 'email',

        # Configure both internal and external redirect URIs
        'OAUTH2_REDIRECT_URI': 'https://pgadmin.onprem.kuberise.dev/oauth2/authorize',
        'SERVER_REDIRECT_URI': 'http://pgadmin-pgadmin4.pgadmin.svc.cluster.local/oauth2/authorize'
    }]

    # Additional security settings
    OAUTH2_TOKEN_VERIFY_SSL = False  # Since we're using internal cluster communication
    SERVER_MODE = True
