apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin
  namespace: pgadmin
data:
  config_local.py: |
    import os
    import logging

    FILE_LOG_LEVEL = logging.INFO
    SERVER_MODE = True
    CONSOLE_LOG_LEVEL = logging.INFO
    MASTER_PASSWORD_REQUIRED = True
    AUTHENTICATION_SOURCES = ['internal', 'oauth2']
    OAUTH2_CONFIG = [
      {
        'OAUTH2_NAME': 'Keycloak',
        'OAUTH2_DISPLAY_NAME': 'Keycloak',
        'OAUTH2_CLIENT_ID': 'pgadmin',
        'OAUTH2_CLIENT_SECRET': 'AB4NBwnv2nDdWPBGpthpMOxG9yfGYVFw',
        'OAUTH2_TOKEN_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/token',
        'OAUTH2_AUTHORIZATION_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/auth',
        'OAUTH2_SERVER_METADATA_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/.well-known/openid-configuration',
        'OAUTH2_API_BASE_URL': 'https://keycloak.onprem.kuberise.dev/',
        'OAUTH2_USERINFO_ENDPOINT': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/userinfo',
        'OAUTH2_SCOPE': 'openid email profile',
        'OAUTH2_USERNAME_CLAIM': 'preferred_username',
        'OAUTH2_LOGOUT_URL': 'https://keycloak.onprem.kuberise.dev/realms/kuberise/protocol/openid-connect/logout?id_token_hint={id_token}&post_logout_redirect_uri=https://pgadmin.onprem.kuberise.dev',
        'OAUTH2_ICON': 'fa-solid fa-unlock',
        'OAUTH2_BUTTON_COLOR': '#f44242',
        'OAUTH2_SSL_CERT_VERIFICATION': False, # for self-signed certificates it should be False
      }
    ]

    DEBUG = True

    # Application log level - one of:
    #   CRITICAL 50
    #   ERROR    40
    #   WARNING  30
    #   SQL      25
    #   INFO     20
    #   DEBUG    10
    #   NOTSET    0
    CONSOLE_LOG_LEVEL = logging.DEBUG

    # Note: This can cause problems when the server is deployed in dynamic IP
    # address hosting environments, such as Kubernetes or behind load
    # balancers. In such cases, this option should be set to False.
    ENHANCED_COOKIE_PROTECTION = False
