replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
  hosts:
    - host: show-env.k8s-showenvd-showenvd-7882095507-664608012.eu-central-1.elb.amazonaws.com
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest

service:
  type: NodePort
  port: 80
