replicaCount: 1

ingress:
  enabled: true
  className: external-nginx
  annotations:
    kubernetes.io/ingress.class: "external-nginx"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"

  hosts:
    - host: show-env.eks.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest

service:
  type: NodePort
  port: 80
