replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"


env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest

service:
  type: NodePort
  port: 80
