

adminUsername: admin
adminPassword: admin
pgSuperuserPassword: superpassword

###### app-of-apps values #####
global:
  environment: dev
  spec:
    source:
      targetRevision: mojtaba/kuberise-chart
    values:
      targetRevision: mojtaba/kuberise-chart

applications:
  raw:
    enabled: true

  cnpg-database:
    enabled: true

helmCharts:
  backstage:
    enabled: true

  keycloak:
    enabled: true

  ingress-nginx:
    enabled: true

  kube-prometheus-stack:
    enabled: true

  loki:
    enabled: true

  promtail:
    enabled: true

  cert-manager:
    enabled: true

  cloudnative-pg:
    enabled: true
