fullnameOverride: show-env-dev

image:
  repository: ghcr.io/kuberise/show-env
  tag: latest

replicaCount: 1

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

ingress:
  enabled: true
  className: nginx
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
  tls:
  - hosts:
    - "show-env-dev.kind.kuberise.dev"
    secretName: wildcard-cert-tls
  hosts:
    - host: show-env-dev.kind.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
