pgadmin4:
  persistentVolume:
    storageClass: gp2
  extraConfigmapMounts:
    - name: configmap
      configMap: pgadmin
      mountPath: /pgadmin4/config_local.py
      subPath: config_local.py
      readOnly: true
