controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  extraArgs:
    default-ssl-certificate: cert-manager/wildcard-tls
    watch-ingress-without-class: false

  ingressClassResource:
    enabled: true
    name: nginx-external
    default: false

  ingressClass: nginx-external
