controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  updateStrategy:
    type: Recreate
    # because in RollingUpdate for any changes, kubernetes will create a new pod and then delete the old one.
    # But the new pod and the old pod will conflict on the same port number. So, we need to use Recreate strategy.
    # This means that if you change configuration of external nginx controller, you will have few seconds of down time.
  ingressClassResource:
    enabled: true
    name: nginx-external
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  ingressClass: nginx-external

  watchIngressWithoutClass: false
  electionID: ingress-controller-leader-external
  ingressClassByName: true
