controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  extraArgs:
    default-ssl-certificate: cert-manager/wildcard-tls
    watch-ingress-without-class: false

  ingressClassResource:
    enabled: true
    name: nginx-external
    default: false
    controllerValue: "k8s.io/ingress-nginx-external"

  ingressClass: nginx-external

  watchIngressWithoutClass: false
  electionID: ingress-controller-leader-external
  ingressClassByName: true  # This ensures exact matching of class names
