controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  ingressClassResource:
    # -- Name of the ingressClass
    name: nginx-external
    # -- Is this ingressClass enabled or not
    enabled: true
    # -- Is this the default ingressClass for the cluster
    default: true

  ingressClass: nginx-external
