# groups:
#   developers:
#     description: "Development team with edit access to dev namespace"
#     namespaces:
#       - name: dev
#         roles:
#           - edit  # Built-in ClusterRole
#       - name: staging
#         roles:
#           - view  # Built-in ClusterRole
#   operators:
#     description: "Operations team with cluster-wide admin access"
#     namespaces:
#       - name: "*"  # All namespaces
#         clusterRoles:  # Using clusterRoles for cluster-wide access
#           - cluster-admin
#   qa-team:
#     description: "QA team with edit access to qa namespace"
#     namespaces:
#       - name: qa
#         roles:
#           - edit
#       - name: staging
#         roles:
#           - view

# users:
#   - name: john.doe
#     email: john.doe@company.domain
#     groups:
#       - developers
#   - name: jane.smith
#     email: jane.smith@company.domain
#     groups:
#       - developers
#       - qa-team
#   - name: bob.admin
#     email: bob.admin@company.domain
#     groups:
#       - operators
