# groups:
#   developers:
#     description: "Development team with edit access to dev namespace"
#     namespaces:
#       - name: dev
#         roles:
#           - edit  # Built-in ClusterRole
#       - name: staging
#         roles:
#           - view  # Built-in ClusterRole
#   operators:
#     description: "Operations team with cluster-wide admin access"
#     namespaces:
#       - name: "*"  # All namespaces
#         clusterRoles:  # Using clusterRoles for cluster-wide access
#           - cluster-admin
#   qa-team:
#     description: "QA team with edit access to qa namespace"
#     namespaces:
#       - name: qa
#         roles:
#           - edit
#       - name: staging
#         roles:
#           - view

# users:
#   - username: john.doe
#     firstName: John
#     lastName: Doe
#     email: john.doe@company.domain
#     groups:
#       - developers
#   - username: jane.smith
#     firstName: Jane
#     lastName: Smith
#     email: jane.smith@company.domain
#     groups:
#       - developers
#       - qa-team
#   - username: bob.admin
#     firstName: Bob
#     lastName: Admin
#     email: bob.admin@company.domain
#     groups:
#       - operators
