# argocd oauth2 client secret has different requirements and is separated from the general template

# ==========================================
# Generate Secret for argocd
# ==========================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-client-secret-generate
spec:
  refreshInterval: "0"
  target:
    name: argocd-random-string
    creationPolicy: Owner
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: password-generator
---
# ==================================================================================================
# Copy secrets for specified namespace
# ==================================================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-secret-copy-argocd
  namespace: argocd
spec:
  secretStoreRef:
    name: k8s-store
    kind: ClusterSecretStore

  refreshInterval: "1h"
  target:
    creationPolicy: Merge
    name: argocd-secret
    template:
      data:
        oidc.keycloak.clientSecret: "{{ `{{ .clientSecret }}` }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd-random-string
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: client-secret-copy-keycloak
  namespace: keycloak
spec:
  secretStoreRef:
    name: k8s-store
    kind: ClusterSecretStore

  refreshInterval: "1h"
  target:
    creationPolicy: Owner
    name: argocd-oauth2-client-secret
    template:
      data:
        client-secret: "{{ `{{ .clientSecret }}` }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: argocd-random-string
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
# Create ServiceAccount for each namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: argocd
---
