apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ $.Release.Namespace }}
      auth:
        serviceAccount:
          name: external-secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: {{ $.Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: {{ $.Release.Namespace }}
{{- range .Values.namespaces }}
  - kind: ServiceAccount
    name: external-secrets
    namespace: {{ . }}
{{- end }}
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
