# ==========================================
# Create ServiceAccount for each namespace
# ==========================================
{{- range .Values.namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: {{ . }}
{{- end }}
