pgadmin4:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
    hosts:
      - host: pgadmin.{{ .Values.global.domain }}
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
      - "*.{{ .Values.global.domain }}"
      secretName: wildcard-cert-tls
