pgadmin4:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: pgadmin.kind.kuberise.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
      - "*.kind.kuberise.dev"
