apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: project1-prd
  sources:
  - chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.11.0
    helm:
      releaseName: sealed-secrets
      valueFiles:
        - $values/app-values/sealed-secrets/sealed-secrets-values-project1-prd.yaml
  - repoURL: https://github.com/Kuberise/kuberise.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        managed: "true"
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
      retry:
        limit: 3
        backoff:
          duration: 30
          factor: 2
          maxDuration: 60
