apiVersion: operators.coreos.com/v2alpha1
kind: Subscription
metadata:
  name: keycloak-operator-subscription
spec:
  channel: alpha
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
