{{- range $name, $app := .Values.externalHelmCharts -}}
{{ if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default $name .name }}-{{ $.Values.global.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.global.spec.project }}
  sources:
  - repoURL:  {{ .repoURL }}
    targetRevision: {{ .targetRevision }}
    chart: {{ default $name .chart }}
    helm:
      valueFiles:
      - $valuesRepo/values/{{ default $name .name }}/values-{{ $.Values.global.env }}.yaml
  - repoURL: {{ $.Values.global.spec.source.repoURL }}
    targetRevision: mojtaba/app-of-apps-helm
    ref: valuesRepo
  destination:
    namespace: {{ default $name .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if default $.Values.global.automated .automated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- end }}
{{- end }}
