{{- range $name, $app := .Values.internalHelmCharts -}}
{{ if .enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default $name .name }}-{{ $.Values.global.env }}
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.global.spec.project }}
  source:
    repoURL:  {{ $.Values.global.spec.source.repoURL }}
    targetRevision: {{ default $.Values.global.spec.source.targetRevision .targetRevision }}
    path: apps/{{ default $name .name }}
    helm:
      valueFiles:
      - ../../values/{{ default $name .name }}/values-{{ $.Values.global.env }}.yaml
  destination:
    namespace: {{ default $name .namespace }}
    server: {{ $.Values.global.spec.destination.server }}
  syncPolicy:
    {{- if default $.Values.global.automated .automated }}
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    {{- end }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- end }}
{{- end }}
