# There are three types of ArgocdApplications: kustomize, helm, and raw. Default is helm
ArgocdApplications:

  keycloak:
    enabled: false

  keycloak-operator:
    enabled: false
    repoURL: https://epam.github.io/edp-helm-charts/stable
    targetRevision: 1.23.0
    chart: keycloak-operator
    namespace: keycloak

  cert-manager:
    enabled: false
    namespace: cert-manager

  vault:
    enabled: false
    repoURL: https://helm.releases.hashicorp.com
    namespace: vault
    targetRevision: 0.28.0
    chart: vault
