persistence:
  enabled: true
service:
  type: LoadBalancer
ingress:
  enabled: true
  className: nginx
  hosts:
    - host: gitea.172.19.0.5.nip.io
      paths:
        - path: /
          pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    cert-manager.io/cluster-issuer: ca-clusterissuer
