useHttps: false

containerPorts:
  http: 80

service:
  type: ClusterIP
  ports:
    http: 80

ingress:
  enabled: true
  className: nginx-internal
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: kuberise.internal
      paths:
        - path: /backend
          pathType: ImplementationSpecific
  tls: []
