expose:
  type: ingress
  ingress:
    tls:
    - hosts:
      - "*.nip.io"
      secretName: wildcard-cert-tls
    hosts:
      core: core.harbor-172-19-0-3.nip.io
      notary: notary.harbor-172-19-0-3.nip.io
    className: nginx
    annotations:
      ingress.kubernetes.io/ssl-redirect: "false"
      ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      cert-manager.io/issuer: "letsencrypt-staging"
externalURL: http://core.harbor-172-19-0-3.nip.io
