{{- if .Values.letsEncrypt.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: {{ .Values.letsEncrypt.email }}
    {{- if eq .Values.letsEncrypt.server "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else if eq .Values.letsEncrypt.server "staging" }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      {{- if eq .Values.letsEncrypt.challenge "http01" }}
      - http01:
          ingress:
            ingressClassName: nginx-external
      {{- else if eq .Values.letsEncrypt.challenge "dns01" }}
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: cloudflare_api_token
      {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-default-crt-letsencrypt
  namespace: cert-manager
spec:
  secretName: ssl-certificate-letsencrypt
  dnsNames:
  {{- range .Values.subdomains }}
  - "{{ . }}.{{ $.Values.domain }}"
  {{- end }}
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
{{- end }}
