configs:
  cm:
    timeout.reconciliation: 5s
    url: https://argocd.{{ .Values.global.domain }}
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.{{ .Values.global.domain }}/realms/platform
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
      apps/Deployment:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources
            - .spec.template.spec.initContainers[].resources
      operators.coreos.com/ClusterServiceVersion:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.install.spec.deployments[].spec.template.spec.containers[].ports[].protocol
      apps/DaemonSet:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources
            - .spec.template.spec.initContainers[].resources
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
    resource.compareoptions: |
      # disables status field diffing in specified resource types
      # 'crd' - CustomResourceDefinitions (default)
      # 'all' - all resources
      # 'none' - disabled
      ignoreResourceStatusField: all
  params:
    server.insecure: true
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
server:
  insecure: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
