configs:
  cm:
    timeout.reconciliation: 5s
    url: https://argocd.onprem.kuberise.dev #FIXME: should be replaced with argocd.{{ .Values.global.domain }} by install.sh script
    oidc.config: | #FIXME: mapper is not done by keycloak operator yet : https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/
      name: Keycloak
      issuer: https://keycloak.onprem.kuberise.dev/realms/platform #FIXME: should be replaced with keycloak.{{ .Values.global.domain }} by install.sh script
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret #FIXME: keycloak user doesn't see applications
      requestedScopes: ["openid", "profile", "email", "groups"] #FIXME: logout doesn't work
      requestedIDTokenClaims:
        groups:
          essential: true
      groupsAttributePath: groups
      logoutURL: https://keycloak.{{ .Values.global.domain }}/auth/realms/platform/protocol/openid-connect/logout?id_token_hint={{token}}&post_logout_redirect_uri={{logoutRedirectURL}}
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          hs = {}
          hs.status = "Progressing"
          hs.message = ""
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              hs.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                hs.message = obj.status.health.message
              end
            end
          end
          return hs
      apps/Deployment:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources
            - .spec.template.spec.initContainers[].resources
      operators.coreos.com/ClusterServiceVersion:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.install.spec.deployments[].spec.template.spec.containers[].ports[].protocol
      apps/DaemonSet:
        ignoreDifferences: |
          jqPathExpressions:
            - .spec.template.spec.containers[].resources
            - .spec.template.spec.initContainers[].resources
      admissionregistration.k8s.io/MutatingWebhookConfiguration:
        ignoreDifferences: |
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
      admissionregistration.k8s.io/ValidatingWebhookConfiguration:
        ignoreDifferences: |
          jqPathExpressions:
            - .webhooks[].clientConfig.caBundle
    resource.compareoptions: |
      # disables status field diffing in specified resource types
      # 'crd' - CustomResourceDefinitions (default)
      # 'all' - all resources
      # 'none' - disabled
      ignoreResourceStatusField: all
  params:
    server.insecure: true
controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
server:
  insecure: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  volumes:
    - name: ca-cert
      configMap:
        name: external-selfsigned-ca-certificate
  volumeMounts:
    - name: ca-cert
      mountPath: /etc/ssl/certs/ca-certificates.crt
      subPath: ca.crt
