replicaCount: 3

ingress:
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer"
  tls:
  - hosts:
    - "*.127.0.0.1.nip.io"
    secretName: wildcard-cert-tls-letsencrypt-staging
  enabled: true
  hosts:
    - host: frontend.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
