replicaCount: 3

ingress:
  tls:
  - hosts:
    - "*.172.19.0.5.nip.io"
    secretName: wildcard-cert-tls
  enabled: true
  hosts:
    - host: frontend.172.19.0.5.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
