replicaCount: 3

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-clusterissuer
  hosts:
    - host: frontend.172.19.0.5.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
