apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca-cert
  namespace: {{ .Release.Namespace }}
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    # Your CA certificate content here
    -----END CERTIFICATE-----
