replicaCount: 2

ingress:
  enabled: true
  annotations:
      cert-manager.io/issuer: "letsencrypt-staging"
  tls:
  - hosts:
    - "*.nip.io"
    secretName: wildcard-cert-tls-letsencrypt-staging
  hosts:
    - host: frontend-tst-172-19-0-3.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
