replicaCount: 1

ingress:
  enabled: true
  tls:
  - hosts:
    - "*.dev.127.0.0.1.nip.io"
    secretName: wildcard-cert-tls
  hosts:
    - host: show-env.dev.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

env:
  Environment: dev
  name: env-show
  PROTOCOL: HTTP

image:
  tag: latest
