controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  extraArgs:
    watch-ingress-without-class: false

  service:
    type: ClusterIP

  ingressClassResource:
    enabled: true
    name: nginx-internal
    default: false

  ingressClass: nginx-internal
