controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  extraArgs:
    watch-ingress-without-class: false

  service:
    type: ClusterIP

  ingressClassResource:
    enabled: true
    name: nginx-internal
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"

  ingressClass: nginx-internal

# to ensure controller knows which class to watch
  watchIngressWithoutClass: false
  electionID: ingress-controller-leader-internal
  ingressClassByName: true  # This ensures exact matching of class names
