helm:
  parameters:
  - name: domain
    value: minikube.kuberise.dev
    forcestring: false
  - name: image.name
    value: ghcr.io/kuberise/show-env
    forcestring: true
  - name: image.tag
    value: latest@sha256:511feff6d0fe6ddd15f7f3ab5d7ddf747a807b5387dd9f7571962d3d7941470a
    forcestring: true
