helm:
  parameters:
  - name: global.domain
    value: airgap.kuberise.dev
    forcestring: false
  - name: image.name
    value: ghcr.io/kuberise/show-env
    forcestring: true
  - name: image.tag
    value: latest@sha256:a414f18dcaf950b6149a99faadda8bce51adf6e925a3a753710166bd1c647b54
    forcestring: true
