helm:
  parameters:
  - name: global.domain
    value: onprem.kuberise.dev
    forcestring: false
  - name: image.name
    value: ghcr.io/kuberise/show-env
    forcestring: true
  - name: image.tag
    value: latest@sha256:611719e390f49fe0e900f07654310ade189186c9b1b98e10b60ea77ffd8bb2eb
    forcestring: true
