# To use DNS01 challenge, you need to set the cloudflare API Token. (or other DNS provider). Otherwise, use self-signed certificates.
# If you want to use self-signed certificates, set default-ssl-certificate: cert-manager/ssl-certificate-selfsigned in ingress-nginx-external/values.yaml
letsEncrypt:
  enabled: false
  server: production
  challenge: dns01

cert-manager:
  image:
    repository: registry:5000/jetstack/cert-manager-controller

  webhook:
    image:
      repository: registry:5000/jetstack/cert-manager-webhook

  cainjector:
    image:
      repository: registry:5000/jetstack/cert-manager-cainjector

  acmesolver:
    image:
      repository: registry:5000/jetstack/cert-manager-acmesolver

  startupapicheck:
    image:
      repository: registry:5000/jetstack/cert-manager-startupapicheck
