apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
spec:
  secretName: keycloak-tls
  dnsNames:
    - "keycloak.{{ .Values.global.domain }}"
    - keycloak-http.keycloak.svc.cluster.local
    - keycloak-http
    - keycloak.kuberise.internal
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
