apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls
  namespace: cert-manager
spec:
  secretName: keycloak-tls
  dnsNames:
    - "keycloak.{{ .Values.domain }}"
    - keycloak-keycloakx-http.keycloak.svc.cluster.local
    - keycloak-keycloakx-http
    - keycloak.kuberise.internal
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
