apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: grafana-client
spec:
  clientId: grafana
  directAccess: true
  realmRef:
    kind: KeycloakRealm
    name: platform-realm
  secret: '$grafana-oauth2-client-secret:client-secret'
  serviceAccount:
    enabled: true
  webUrl: 'https://grafana.onprem.kuberise.dev/'
  redirectUris:
    - 'https://grafana.onprem.kuberise.dev/login/generic_oauth'
