apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  instances: 1
