apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
spec:
  instances: 1
  externalDatabase:
    enabled: true
  keycloakDeploymentSpec:
    env:
      - name: DB_VENDOR
        value: postgres
      - name: DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: keycloak-db-secret
            key: POSTGRES_DATABASE
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: keycloak-db-secret
            key: POSTGRES_USERNAME
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: keycloak-db-secret
            key: POSTGRES_PASSWORD
      - name: DB_ADDR
        valueFrom:
          secretKeyRef:
            name: keycloak-db-secret
            key: POSTGRES_HOST
