apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: pgadmin-client
  namespace: keycloak
spec:
  authorizationServicesEnabled: true
  clientId: pgadmin
  directAccess: false
  realmRef:
    kind: KeycloakRealm
    name: platform-realm
  secret: '$keycloak-pgadmin-oauth2-client-secret:CLIENT_SECRET'
  serviceAccount:
    enabled: true
  webUrl: 'https://pgadmin.onprem.kuberise.dev/'
  redirectUris:
    - 'https://pgadmin.onprem.kuberise.dev/*'
