apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: pgadmin-client
spec:
  authorizationServicesEnabled: true
  clientId: pgadmin
  directAccess: false
  realmRef:
    kind: KeycloakRealm
    name: platform-realm
  secret: '$pgadmin-oauth2-client-secret:client-secret'
  serviceAccount:
    enabled: true
  webUrl: 'https://pgadmin.{{ .Values.global.domain }}/'
  redirectUris:
    - 'https://pgadmin.{{ .Values.global.domain }}/*'
