fullnameOverride: todolist-frontend-dev

image:
  repository: ghcr.io/kuberise/todolist-webapp
  tag: "latest"

env:
  REACT_APP_BACKEND_URL: http://todolist-backend-dev.todolist-backend-dev.svc.cluster.local

replicaCount: 1

ingress:
  enabled: true
  className: nginx
  annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
  tls:
  - hosts:
    - "todolist-frontend-dev.kind.kuberise.dev"
    secretName: wildcard-cert-tls
  hosts:
    - host: todolist-frontend-dev.kind.kuberise.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
