pgadmin4:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "ca-clusterissuer-external"
    hosts:
      - host: pgadmin.minikube.kuberise.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
    - hosts:
      - "*.minikube.kuberise.dev"
      secretName: wildcard-cert-tls
