apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-database
  namespace: cloudnative-pg
spec:
  instances: 1

  bootstrap:

  storage:
    size: 1Gi

  monitoring:
    enablePodMonitor: true

  enableSuperuserAccess: true

  managed:
    roles:
    - name: app
      createdb: true
      login: true
