pgadmin4:
  extraConfigmapMounts:
    - name: configmap
      configMap: pgadmin
      mountPath: /pgadmin4/config_local.py
      subPath: config_local.py
      readOnly: true
    - name: ca-cert-config
      mountPath: /etc/ssl/certs/custom-ca.crt
      subPath: ca.crt
      configMap: pgadmin-ca-cert
      readOnly: true
