keycloakx:
  http:
    relativePath: "/"
  command:
    - "/opt/keycloak/bin/kc.sh"
    - "--verbose"
    - "start-dev"
    - "--http-enabled=false" # Only HTTPS is enabled
    - "--hostname-strict=false"
    - "--features=token-exchange"

  metrics:
    enabled: true

  serviceMonitor:
    enabled: true
    path: /metrics
    labels:
      app.kubernetes.io/part-of: kube-prometheus-stack

  extraEnv: |
    - name: JAVA_OPTS_APPEND
      value: >-
        -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
    - name: KC_DB_URL
      value: "jdbc:postgresql://cnpg-database-rw.cloudnative-pg.svc.cluster.local:5432/app"
    - name: KC_DB
      value: postgres
    - name: HTTPS_CERTIFICATE_FILE
      value: /etc/tls/tls.crt
    - name: HTTPS_CERTIFICATE_KEY_FILE
      value: /etc/tls/tls.key

  extraEnvFrom: |
    - secretRef:
        name: pg-secret
    - secretRef:
        name: admin-secret

  extraVolumes:
    - name: keycloak-tls
      secret:
        secretName: keycloak-tls
  extraVolumeMounts:
    - name: keycloak-tls
      mountPath: /etc/tls
      readOnly: true
